import { LucideIcon, Accessibility, AlertTriangle, Atom, Badge, BookOpen, 
    Bot, Box, Boxes, Briefcase, Building, Calculator, Calendar, ChartBar, ChartLine, 
    CheckCircle, CircleDot, ClipboardCheck, ClipboardList, Cloud, Code, Coffee, Cog, 
    Contact, Container, Cross, Database, Diamond, DraftingCompass, Factory, Figma, 
    FileSignature, FileSpreadsheet, FileText, Filter, Folder, GanttChart, Gavel, GitBranch, 
    Globe, Handshake, Heart, HeartHandshake, Image, Laptop, Lightbulb, Mail, MessageCircle, 
    Microscope, Monitor, MonitorPlay, MousePointer, MousePointerClick, Paintbrush, Pen, PenTool, PencilRuler, 
    Phone, PhoneOutgoing, PiggyBank, Pill, Presentation, Receipt, Ruler, Scan, School, Scroll, Search, Server, 
    Share2, ShieldCheck, Smartphone, Stethoscope, Table, Tablet, Target, Terminal, Ticket, TrendingUp, Type, User, 
    UserCheck, UserPlus, UserSearch, Users, Video, Wallet, Wrench, Zap, LayoutDashboard, Languages, LayoutGrid, LifeBuoy, Layout,
    HeartPulse, Banknote, Megaphone, GraduationCap, Palette, Scale, Headphones, Eye, EyeClosed, BadgeCheck, BadgeAlert, BriefcaseBusiness } from "lucide-react";

const icons : Record<string, LucideIcon> = {
    "accessibility" : Accessibility,    
    "alert-triangle" : AlertTriangle,      
    "atom" : Atom,
    "badge" : Badge,    
    "badge-check" : BadgeCheck,        
    "badge-alert" : BadgeAlert,        
    "book-open" : BookOpen,           
    "bot" : Bot,
    "box" : Box,
    "boxes" : Boxes,
    "briefcase" : Briefcase,
    "briefcase-business" : BriefcaseBusiness,
    "building" : Building,         
    "calculator" : Calculator,          
    "calendar" : Calendar,
    "chart-bar" : ChartBar,        
    "chart-line" : ChartLine,          
    "check-circle" : CheckCircle,
    "circle-dot" : CircleDot,       
    "clipboard-check" : ClipboardCheck,     
    "clipboard-list" : ClipboardList,
    "cloud" : Cloud,            
    "code" : Code,                
    "coffee" : Coffee,
    "cog" : Cog,              
    "contact" : Contact,             
    "container" : Container,
    "cross" : Cross,            
    "database" : Database,            
    "diamond" : Diamond,
    "drafting-compass" : DraftingCompass, 
    "eye" : Eye,
    "eye-closed": EyeClosed,
    "factory" : Factory,             
    "figma" : Figma,
    "file-signature" : FileSignature,   
    "file-spreadsheet" : FileSpreadsheet,    
    "file-text" : FileText,
    "filter" : Filter,           
    "folder" : Folder,              
    "gantt-chart" : GanttChart,
    "gavel" : Gavel,            
    "git-branch" : GitBranch,          
    "globe" : Globe,
    "handshake" : Handshake,        
    "heart" : Heart,               
    "heart-handshake" : HeartHandshake,
    "image" : Image,            
    "languages" : Languages,           
    "layout" : Layout,
    "layout-dashboard" : LayoutDashboard, 
    "layout-grid" : LayoutGrid,         
    "life-buoy" : LifeBuoy,
    "lightbulb" : Lightbulb,        
    "mail" : Mail,                
    "message-circle" : MessageCircle,
    "microscope" : Microscope,       
    "monitor" : Monitor,             
    "monitor-play" : MonitorPlay,
    "mouse-pointer" : MousePointer,    
    "mouse-pointer-click" : MousePointerClick, 
    "paintbrush" : Paintbrush,
    "pen" : Pen,              
    "pen-tool" : PenTool,            
    "pencil-ruler" : PencilRuler,
    "phone" : Phone,            
    "phone-outgoing" : PhoneOutgoing,      
    "piggy-bank" : PiggyBank,
    "pill" : Pill,             
    "presentation" : Presentation,        
    "receipt" : Receipt,
    "ruler" : Ruler,            
    "scan" : Scan,                
    "school" : School,
    "scroll" : Scroll,           
    "search" : Search,              
    "server" : Server,
    "share-2" : Share2,          
    "shield-check" : ShieldCheck,        
    "smartphone" : Smartphone,
    "stethoscope" : Stethoscope,      
    "table" : Table,               
    "tablet" : Tablet,
    "target" : Target,           
    "terminal" : Terminal,            
    "ticket" : Ticket,
    "trending-up" : TrendingUp,      
    "type" : Type,                
    "user" : User,
    "user-check" : UserCheck,       
    "user-plus" : UserPlus,           
    "user-search" : UserSearch,
    "users" : Users,            
    "video" : Video,               
    "wallet" : Wallet,
    "wrench" : Wrench,           
    "zap" : Zap, 
    "laptop": Laptop,
    "heart-pulse": HeartPulse,
    "banknote": Banknote,
    "megaphone": Megaphone,
    "graduation-cap": GraduationCap,
    "palette": Palette,
    "scale": Scale,
    "headphones": Headphones,
    "Other": Folder,
}

export {icons};